[package]
name = "irony"
version = "0.1.0"
authors = ["Amanjeev Sethi <aj@amanjeev.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
